@echo off
cd /D "D:\Sistemas\Pax Primavera\api-teste" && start cmd /k "title api-teste && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-spa" && start cmd /k "title pax-spa && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-login" && start cmd /k "title pax-login && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-home" && start cmd /k "title pax-home && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-associado" && start cmd /k "title pax-associado && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-venda" && start cmd /k "title pax-venda && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-financeiro" && start cmd /k "title pax-financeiro && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-cobranca" && start cmd /k "title pax-cobranca && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-cadastro" && start cmd /k "title pax-cadastro && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-suporte" && start cmd /k "title pax-suporte && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-parcelas" && start cmd /k "title pax-parcelas && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-boletos" && start cmd /k "title pax-boletos && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-ranking" && start cmd /k "title pax-ranking && npm start"
cd /D "D:\Sistemas\Pax Primavera\pax-relatorio" && start cmd /k "title pax-relatorio && npm start"
